const SCREENS = {
    EXPLORE: "Khám phá",
    LOGIN: 'Login',
    SIGNUP: 'Signup',
    ACCOUNT: "Tài khoản",
    STUDYGROUP:"Nhóm học tập",
    LIBRARY:"Thư Viện",
    REPORT:"Báo cáo",
    EXPLORE_SEARCH: "Tìm kiếm",
    EXPLORE_TAB: "Tab khám phá",
    USER_TAB: "Tab người dùng",
    ADMIN_TAB: "Tab quản trị",
    QUIZ_CREATION:"Tạo bài kiểm tra",
    QUESTION_SETTING:"Cài đặt câu hỏi",
    FLASHCARD_SET_DETAIL: "Chi tiết bộ flashcard",
    FLASHCARD_STUDY: "Học flashcard",
    ADD_FLASHCARD: "Thêm FlashCard",
    FlashCardPage: 'FlashCardPage',
    SharedQuizz: 'SharedQuizz',
    ReportDetail: 'Chi tiết báo cáo',
    CREATE_STUDY_GROUP: "Tạo nhóm học tập",
    STUDY_GROUP_DETAIL: "Chi tiết nhóm học tập",
    RANKING: "Xếp hạng",
    ENDQUIZ: "Kết thúc bài kiểm tra",
    QUESTION_PLAY: "Trình phát câu hỏi",
    GROUP_MESSAGE:"Nhóm nhắn tin",
    GROUP_MEMBERS:"Thành viên nhóm",
    QUIZ_DETAIL: "Chi tiết bài kiểm tra",
    LOBBY: "Sảnh chờ",
    QUIZ_REPORT: "Báo cáo bài kiểm tra",
    QUESTION_PLAY_SETTING: "Cài đặt trình phát câu hỏi (Chủ trì)",
    ADMIN_QUIZZES: "Quản lý quizz",
    ADMIN_PACKAGES: "Quản lý gói / doanh thu",
    ADMIN_USERS: "Quản lý người dùng",
    ADMIN_ACCOUNT: "Tài khoản admin",
    AUTH_STACK: 'AuthStack',
    USER_STACK: 'UserStack',
    ADMIN_STACK: 'AdminStack',
    SELECT_QUIZ_FOR_FLASHCARD: 'SelectQuizForFlashcard',
    SELECT_QUESTIONS_FOR_FLASHCARD: 'SelectQuestionsForFlashcard',
    REPORT_HISTORY: 'Lịch sử báo cáo',
    USER_PACKAGE: 'Gói',
    REVENUE: 'Doanh thu',
    CREATE_PACKAGE: 'Tạo gói',
    QUIZ_REPORT_DETAIL: 'Chi tiết báo cáo quiz',
    UPDATE_ACCESS:'Cập nhật quyền truy cập'
};
  
  export default SCREENS;
  
