const SCREENS = {
    EXPLORE: "Khám phá",
    LOGIN: "Đăng ký",
    SIGNUP: "Đăng nhập",
    ACCOUNT: "Tài khoản",
    STUDYGROUP:"Nhóm học tập",
    LIBRARY:"Thư Viện",
    REPORT:"Báo cáo",
    EXPLORE_SEARCH: "Tìm kiếm",
    EXPLORE_TAB: "Tab khám phá",
    USER_TAB: "Tab người dùng",
    ADMIN_TAB: "Tab quản trị",
    QUIZ_CREATION:"Tạo bài kiểm tra",
    QUESTION_SETTING:"Cài đặt câu hỏi",
    FLASHCARD_SET_DETAIL: "Chi tiết bộ flashcard",
    ADD_FLASHCARD: "Thêm FlashCard",
    FlashCardPage: 'FlashCardPage',
    SharedQuizz: 'SharedQuizz',
    ReportDetail: 'Chi tiết báo cáo',
    CREATE_STUDY_GROUP: "Tạo nhóm học tập",
    STUDY_GROUP_DETAIL: "Chi tiết nhóm học tập",
    RANKING: "Xếp hạng",
    ENDQUIZ: "Kết thúc bài kiểm tra",
    QUESTION_SETTING: "Cài đặt câu hỏi",
    QUESTION_PLAY: "Trình phát câu hỏi",
    GROUP_MESSAGE:"Nhóm nhắn tin",
    GROUP_MEMBERS:"Thành viên nhóm",
    QUIZ_DETAIL: "Chi tiết bài kiểm tra",
    LOBBY: "Sảnh chờ",
    QUIZ_REPORT: "Báo cáo bài kiểm tra",
  };
  
  export default SCREENS;
  